# name: "Cronjob"
# on:
#   schedule:
#     - cron: '15 */6 * * *'

# jobs:
#   update-weather:
#     permissions: write-all
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Generate README
#         uses: vanthuan0504/weather-forecast@v1.0.0
#         with:
#           city: QuangNam
#           days: 2
#           weather-api-key: ${{ secrets.WEATHER_API_KEY }}
#           template-file: 'README.md.template'
#           out-file: 'README.md'
#       - name: Commit
#         run: |
#           git config user.name github-actions
#           git config user.email github-actions@github.com
#           git add .
#           git commit -m "update"
#           git push origin main
